name: AdminHunt
version: ${project.version}
description: ${project.description}
database: true

authors: [Tom Powell (zifnab06)]
website: ${project.url}

main: net.zifnab06.AdminHunt.AdminHunt


commands:
  pvp-toggle:
    description: Toggle Player's PVP Status
    permission: adminhunt.toggle
    usage: |
           /<command> player - toggle player's PVP status
permissions:
  adminhunt.toggle:
    description: Allow use of /toggle-pvp command
